#
---
apiVersion: '1.1.0'
changeDate: '2019-07-15'
beaconId: 'progenetix-beacon'
description: |
  A forward looking implementation for Beacon+ development, with focus on structural variants and metadata.
service_info:
  id: org.progenetix.beacon
  name: 'Beacon+ interface to Progenetix cancer genome profile collections'
  type: 'urn:ga4gh:beacon'
  description: |
    Beacon+ provides a forward looking implementation of the Beacon API, with focus on structural variants and metadata based on the cancer and reference genome profiling data represented in the Progenetix oncogenomic data resource (http://progenetix.org).
  documentationUrl: 'https://info.progenetix.org/tags/Beacon.html'
  serviceUrl: "https://beacon.progenetix.org/"
  serviceType: "GA4GHBeacon"
  welcomeUrl: "https://beacon.progenetix.org/ui/"
  alternativeUrl: "https://progenetix.org"
  contactUrl: 'mailto:contact@progenetix.org'
  version: '1.1.0'
  open: true
  organization:
    id: 'org.baudisgroup'
    name: 'baudisgroup at UZH and SIB'
    description: |
      The "Theoretical Cytogenetics and Oncogenomics" group at the University of Zurich (UZH) and the Swiss Institute of Bioinformatics (SIB) performs research in cancer genomics and provides bioinformatics tools and cancer genome data resources to the scientific community.
    address: "Department of Molecular Life Sciences, University of Zurich, Winterthurerstrasse 190, CH-8057 Zurich, Switzerland"
    welcomeUrl: 'https://info.baudisgroup.org'
    info:
      provider:
        - 'Michael Baudis'
        - 'Theoretical Cytogenetics and Oncogenomics, Department of Molecular Life Sciences, University of Zurich'
        - 'http://www.imls.uzh.ch/en/research/baudis.html'
        - 'http://info.baudisgroup.org/'
        - 'Swiss Institute of Bioinformatics - SIB'
        - 'http://www.sib.swiss/baudis-michael' 
datasets:
  - id: arraymap
    description: "arraymap cancer CNV dataset"
    variantCount: 1
    info:
      authorized: true
      accessType: PUBLIC
  - id: progenetix
    description: "Progenetix cancer genome profiles"
    variantCount: 1
    info:
      authorized: true
      accessType: PUBLIC
  - id: tcga
    description: "TCGA CNVs"
    variantCount: 1
    info:
      authorized: true
      accessType: PUBLIC
  - id: dipg
    description: "DIPG data from publication Mackay et al., 2017"
    variantCount: 1
    info:
      authorized: true
      accessType: PUBLIC
technology_keys:
  - ccgh
  - acgh
  - wes
  - wgs
  - ngs
  - genomes
geo_keys:
  - city
  - country
  - continent
  - latitude
  - longitude
technology_labels:
  ccgh: 'Chromosomal CGH'
  acgh: 'Genomic Array'
  wes: 'Whole Exome Sequencing'
  wgs: 'Whole Genome Sequencing'
collection_names:
  callset_collection: callsets
  variant_collection: variants
  biosample_collection: biosamples
  individual_collection: individuals
handover_types:
  cnvhistogram:
    id: 'pgx:handover:cnvhistogram'
    label: "CNV Histogram"
    description: "create a CNV histogram from matched callsets"
    handover_method: 'callsets::_id'
  biosamplesdata:
    id: 'pgx:handover:biosamplesdata'
    label: "Biosamples"
    description: "retrieve data of the biosamples matched by the query"
    handover_method: 'biosamples::_id'
  individualsdata:
    id: 'pgx:handover:individualsdata'
    label: "Individuals"
    description: "retrieve data of the individuals matched by the query"
    handover_method: 'individuals::_id'
  variantsdata:
    id: 'pgx:handover:variantsdata'
    label: "Variants"
    description: "retrieve data of the variants matched by the query"
    handover_method: 'variants::_id'
  callsetsvariants:
    id: 'pgx:handover:callsetsvariants'
    label: "Callsets Variants"
    description: "export all variants of matched callsets - potentially huge dataset..."
    handover_method: 'callsets::_id'
  progenetixtools:
    id: 'pgx:handover:progenetixtools'
    label: "Progenetix Interface"
    description: "hand the data over to the Progenetix interface for visualization and additional information"
    handover_method: 'callsets::_id'
    script_path_web: '/cgi-bin/pgx_process.cgi'
genome_assemblies:
  - 'GRCh38'
url: 'https://beacon.progenetix.org/beacon/info/'
url_base: 'https://progenetix.org'
url_alt: 'https://beacon.arraymap.org/beacon/info/'
url_logo: 'https://progenetix.org/p/progenetix.png'
actions:
  - handover
handover_db: progenetix
handover_coll: querybuffer
max_distinct_variants: 20
