---
service_info:
  id: org.progenetix.beacon
  name: 'Progenetix Cancer Genomics Beacon+'
  type: 'urn:ga4gh:beacon'
  description: |
    Beacon+ provides a forward looking implementation of the Beacon API, with focus on structural variants and metadata based on the cancer and reference genome profiling data represented in the Progenetix oncogenomic data resource (https://progenetix.org).
  documentationUrl: 'https://info.progenetix.org/tags/Beacon.html'
  serviceUrl: "https://beacon.progenetix.org/"
  serviceType: "GA4GHBeacon"
  welcomeUrl: "https://beacon.progenetix.org/ui/"
  alternativeUrl: "https://progenetix.org"
  contactUrl: 'mailto:contact@progenetix.org'
  version: '1.1.0'
  open: true
  organization:
    id: 'org.baudisgroup'
    name: 'baudisgroup at UZH and SIB'
    description: |
      The "Theoretical Cytogenetics and Oncogenomics" group at the University of Zurich (UZH) and the Swiss Institute of Bioinformatics (SIB) performs research in cancer genomics and provides bioinformatics tools and cancer genome data resources to the scientific community.
    address: "Department of Molecular Life Sciences, University of Zurich, Winterthurerstrasse 190, CH-8057 Zurich, Switzerland"
    welcomeUrl: 'https://info.baudisgroup.org'
    logoUrl: 'https://progenetix.org/p/progenetix.png'
    info:
      provider:
        - 'Michael Baudis'
        - 'Theoretical Cytogenetics and Oncogenomics, Department of Molecular Life Sciences, University of Zurich'
        - 'http://www.imls.uzh.ch/en/research/baudis.html'
        - 'http://info.baudisgroup.org/'
        - 'Swiss Institute of Bioinformatics - SIB'
        - 'http://www.sib.swiss/baudis-michael' 

id: 'org.progenetix.beacon'
name: 'Progenetix Cancer Genomics Beacon+'
apiVersion: '1.1.0'
version: 2020-01-10
description:  |
  Beacon+ provides a forward looking implementation of the Beacon API, with focus on structural variants and metadata based on the cancer and reference genome profiling data represented in the Progenetix oncogenomic data resource (https://progenetix.org).
welcomeUrl: 'https://beacon.progenetix.org/ui/'
alternativeUrl: "https://progenetix.org"
createDateTime: 2015-11-13
updateDateTime: 2020-01-10
organization:
  id: 'org.baudisgroup'
  name: 'baudisgroup at UZH and SIB'
  description: |
    The "Theoretical Cytogenetics and Oncogenomics" group at the University of Zurich (UZH) and the Swiss Institute of Bioinformatics (SIB) performs research in cancer genomics and provides bioinformatics tools and cancer genome data resources to the scientific community.
  address: "Department of Molecular Life Sciences, University of Zurich, Winterthurerstrasse 190, CH-8057 Zurich, Switzerland"
  welcomeUrl: 'https://info.baudisgroup.org'
  contactUrl: 'mailto:contact@progenetix.org'
  logoUrl: 'https://progenetix.org/p/progenetix.png'
sampleAlleleRequests:
  - datasetIds:
      - arraymap
    assemblyId: GRCh38
    referenceName: '9'
    startMin: 18000000
    startMax: 21975098
    endMin: 21967753
    endMax: 26000000
    variantType: "DEL"
    filters:
      - "icdom-94403"
  - datasetIds:
      - dipg
    assemblyId: GRCh38
    referenceName: '17'
    start: 7577121
    alternateBases: "A"
    referenceBases: "G"
    filters:
      - "icdot-C71.7"
technology_keys:
  - ccgh
  - acgh
  - wes
  - wgs
  - ngs
  - genomes
geo_keys:
  - city
  - country
  - continent
  - latitude
  - longitude
technology_labels:
  ccgh: 'Chromosomal CGH'
  acgh: 'Genomic Array'
  wes: 'Whole Exome Sequencing'
  wgs: 'Whole Genome Sequencing'
collection_names:
  callset_collection: callsets
  variant_collection: variants
  biosample_collection: biosamples
  individual_collection: individuals
genome_assemblies:
  - 'GRCh38'
  - '2019-nCoV'
url: 'https://beacon.progenetix.org/ui/'
url_base: 'https://progenetix.org'
url_alt: 'https://beacon.arraymap.org/ui/'
url_logo: 'https://progenetix.org/p/progenetix.png'
document_base: '/Library/WebServer/Documents'
actions:
  - handover
handover_db: progenetix
handover_coll: querybuffer
max_distinct_variants: 20
paths:
  dir_tmp_base_path: '/Library/WebServer/Documents/tmp'
  web_tmp_base_path: '/tmp'
output_params:
  color_var_snv_hex: '#EE00DD'
  color_var_snv_rgb: '238,0,221'
  color_var_break_hex: '#EE00DD'
  color_var_break_rgb: '238,0,221'
  color_var_dup_hex: '#FFC633'
  color_var_dup_rgb: '255,198,51'
  color_var_del_hex: '#33A0FF'
  color_var_del_rgb: '51,160,255'
  color_var_amp_hex: '#FF6600'
  color_var_amp_rgb: '255,102,0'
  color_var_homoloss_hex: '#0033CC'
  color_var_homoloss_rgb: '0,51,204'

