---
handover_types:
  cnvhistogram:
    id: 'pgx:handover:cnvhistogram'
    label: "CNV Histogram"
    description: "create a CNV histogram from matched callsets"
    handover_method: 'callsets::_id'
  biosamplesdata:
    id: 'pgx:handover:biosamplesdata'
    label: "Biosamples"
    description: "retrieve data of the biosamples matched by the query"
    handover_method: 'biosamples::_id'
  individualsdata:
    id: 'pgx:handover:individualsdata'
    label: "Individuals"
    description: "retrieve data of the individuals matched by the query"
    handover_method: 'individuals::_id'
  variantsdata:
    id: 'pgx:handover:variantsdata'
    label: "Variants"
    description: "retrieve variants matched by the query"
    handover_method: 'variants::_id'
  callsetsvariants:
    id: 'pgx:handover:callsetsvariants'
    label: "Callsets Variants"
    description: "export all variants of matched callsets - potentially huge dataset..."
    handover_method: 'callsets::_id'
  progenetixtools:
    id: 'pgx:handover:progenetixtools'
    label: "Progenetix Interface"
    description: "hand the data over to the Progenetix interface for visualization and additional information"
    handover_method: 'callsets::_id'
    script_path_web: '/cgi-bin/pgx_process.cgi'
  UCSClink:   
    id: 'pgx:handover:bedfile2ucsc'
    label: "Variants in UCSC"
    description: "map variants matched by the query to the UCSC browser"
    handover_method: 'variants::_id'
  queryaggregation:   
    id: 'pgx:handover:queryaggregation'
    label: "Aggregate Query"
    description: "Start new query limited to the current samples"
    handover_method: 'callsets::_id'
    script_path_web: 'http://beacon.progenetix.org/ui/'
